package com.pixovid.backend.template.dto;

import com.pixovid.backend.storage.StorageService;
import com.pixovid.backend.template.TemplateBlock;
import java.time.LocalDateTime;

public record TemplateBlockResponse(
    String id,
    String templateId,
    int order,
    double startSec,
    double endSec,
    int track,
    String prompt,
    String model,
    Integer duration,
    String resolution,
    String aspectRatio,
    String startImageKey,
    String endImageKey,
    String swappedStartKey,
    String swappedEndKey,
    String videoKey,
    String sourceVideoKey,
    double cropStart,
    Double cropEnd,
    String linkGroupId,
    boolean faceSwapStart,
    boolean faceSwapEnd,
    int avatarSlot,
    String swapContext,
    boolean lipsync,
    String swapModel,
    LocalDateTime createdAt,
    LocalDateTime updatedAt,
    String startImageUrl,
    String endImageUrl,
    String swappedStartUrl,
    String swappedEndUrl,
    String videoUrl,
    String sourceVideoUrl) {

  public static TemplateBlockResponse of(TemplateBlock b, StorageService storage) {
    return new TemplateBlockResponse(
        b.getId(),
        b.getTemplate().getId(),
        b.getOrder(),
        b.getStartSec(),
        b.getEndSec(),
        b.getTrack(),
        b.getPrompt(),
        b.getModel(),
        b.getDuration(),
        b.getResolution(),
        b.getAspectRatio(),
        b.getStartImageKey(),
        b.getEndImageKey(),
        b.getSwappedStartKey(),
        b.getSwappedEndKey(),
        b.getVideoKey(),
        b.getSourceVideoKey(),
        b.getCropStart(),
        b.getCropEnd(),
        b.getLinkGroupId(),
        b.isFaceSwapStart(),
        b.isFaceSwapEnd(),
        b.getAvatarSlot(),
        b.getSwapContext(),
        b.isLipsync(),
        b.getSwapModel(),
        b.getCreatedAt(),
        b.getUpdatedAt(),
        b.getStartImageKey() != null ? storage.getPublicUrl(b.getStartImageKey()) : null,
        b.getEndImageKey() != null ? storage.getPublicUrl(b.getEndImageKey()) : null,
        b.getSwappedStartKey() != null ? storage.getPublicUrl(b.getSwappedStartKey()) : null,
        b.getSwappedEndKey() != null ? storage.getPublicUrl(b.getSwappedEndKey()) : null,
        b.getVideoKey() != null ? storage.getPublicUrl(b.getVideoKey()) : null,
        b.getSourceVideoKey() != null ? storage.getPublicUrl(b.getSourceVideoKey()) : null);
  }
}
